### ISSUE TITLE
Individual order trades not captured

### ISSUE THREAD

**Issue by jimmynguyc** [bitx/bitx-ruby#4]
The ```trades``` attribute from the ```GET https://api.mybitx.com/api/1/orders/:id``` API is not being captured.

**Comment by jimmynguyc** [comment]
https://github.com/bitx/bitx-ruby/pull/5

**Comment by franc** [comment]
thanks!

**Comment by jimmynguyc** [comment]
:+1:

**Comment by jimmynguyc** [comment]
@franc ironically the GET ORDER endpoint stopped returning "trades" all of the sudden. 

The documentation remains the same though https://bitx.co/api#orders-get-order. I tried to create support tickets but no response. Any chance you could notify the developers?

**Comment by franc** [comment]
@jimmynguyc the endpoint didn't change.

If the order has any trades (ie, Base and Counter != "0.00") it will return a list of trades.
For no trades, it omits the empty list.

So I suspect you testing the response with an Order with no trades?

**Comment by jimmynguyc** [comment]
You're right .. it works :) 

I might be using the old version of the gem :p

**Comment by franc** [comment]
ah, yeah, i will have to update the gem version

**Comment by franc** [comment]
0.2.4 should work

**Comment by jimmynguyc** [comment]
Weird I was using master branch. Nvm will check later.   

--  
Jimmy Ngu

Mobile: +6 012 6769097
Skype: jimmynguyc
Website: http://www.jimmyngu.com
